#-------------------------------------------------------------
# NVM
#-------------------------------------------------------------

. ~/.nvm/nvm.sh

#-------------------------------------------------------------
# TMUX
#-------------------------------------------------------------

alias tmux="tmux -2"
alias tn="tmux new -s"
alias ta="tmux attach -t"
alias ts="tmux switch -t"
alias tl="tmux ls"

#-------------------------------------------------------------
# SYSTEM
#-------------------------------------------------------------

export EDITOR=vim
export TERM=screen-256color
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
